# Generated by Django 4.2.3 on 2023-08-13 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisements', '0004_advertisements_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisements',
            name='image',
            field=models.ImageField(blank=True, upload_to='advertisements/', verbose_name='Изображение'),
        ),
    ]
